name: ci

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:

  build:
    runs-on: [ ubuntu-latest ]
    container:
      image: cjdilks/largex-eic:dev
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: config
        run: |
          source env.sh
          echo "MSTWPDF_HOME=${MSTWPDF_HOME}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MSTWPDF_HOME}" >> $GITHUB_ENV
      - name: compile
        run: make
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            LargexDict_rdict.pcm
            libLargex.so
            mstwpdf/*.o
            mstwpdf/*.so
            src/LargexDict.cxx

  fastsim-macro:
    needs: [ build ]
    runs-on: [ ubuntu-latest ]
    container:
      image: cjdilks/largex-eic:dev
      options: --user root
    strategy:
      matrix:
        include:
          - name: coverage
            analysis: analysis_coverage.C
            postprocess: post_process_coverage.C
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: config
        run: |
          source env.sh
          echo "MSTWPDF_HOME=${MSTWPDF_HOME}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MSTWPDF_HOME}" >> $GITHUB_ENV
      - name: get-artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
      - name: analysis
        #env:
          #S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          #S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        run: root -b -q macro/ci/${{ matrix.analysis }}'("macro/ci/files.config",5,41,25,"fastsim.${{ matrix.name }}",false)'
      - name: postprocess
        run: root -b -q macro/ci/${{ matrix.postprocess }}'("out/fastsim.${{ matrix.name }}.root")'
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fastsim-${{ matrix.name }}-plots
          path: |
            out/fastsim.${{ matrix.name }}.images

#  fastsim-y-minima:
#    needs: [ build ]
#    runs-on: [ ubuntu-latest ]
#    container:
#      image: cjdilks/largex-eic:dev
#      options: --user root
#    steps:
#      - name: checkout
#        uses: actions/checkout@v2
#      - name: config
#        run: |
#          source env.sh
#          echo "MSTWPDF_HOME=${MSTWPDF_HOME}" >> $GITHUB_ENV
#          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MSTWPDF_HOME}" >> $GITHUB_ENV
#      - name: get-artifacts
#        uses: actions/download-artifact@v2
#        with:
#          name: build-artifacts
#      - name: analysis
#        run: root -b -q macro/ci/analysis_yRatio.C
#      - name: postprocess
#        run: root -b -q macro/ci/postprocess_yRatio.C
#      - name: artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: fastsim-y-minima-ratio-plots
#          path: |
#            out/yRatio.images/yRatio*.png
#
#  fastsim-resolutions:
#    needs: [ build ]
#    runs-on: [ ubuntu-latest ]
#    container:
#      image: cjdilks/largex-eic:dev
#      options: --user root
#    steps:
#      - name: checkout
#        uses: actions/checkout@v2
#      - name: config
#        run: |
#          source env.sh
#          echo "MSTWPDF_HOME=${MSTWPDF_HOME}" >> $GITHUB_ENV
#          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MSTWPDF_HOME}" >> $GITHUB_ENV
#      - name: get-artifacts
#        uses: actions/download-artifact@v2
#        with:
#          name: build-artifacts
#      - name: analysis
#        run: root -b -q macro/ci/analysis_resolution.C
#      - name: postprocess
#        run: root -b -q macro/ci/postprocess_resolution.C
#      - name: artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: fastsim-resolution-plots
#          path: |
#            out/resolution.images/*.pdf
#
#  fullsim-coverage:
#    needs: [ build ]
#    runs-on: [ ubuntu-latest ]
#    container:
#      image: cjdilks/largex-eic:dev
#      options: --user root
#    steps:
#      - name: checkout
#        uses: actions/checkout@v2
#      - name: config
#        run: |
#          source env.sh
#          echo "MSTWPDF_HOME=${MSTWPDF_HOME}" >> $GITHUB_ENV
#          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MSTWPDF_HOME}" >> $GITHUB_ENV
#      - name: get-artifacts
#        uses: actions/download-artifact@v2
#        with:
#          name: build-artifacts
#      - name: analysis
#        env:
#          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
#          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
#        run: root -b -q macro/ci/analysis_coverage.C'("macro/ci/s3files.config",5,41,25,"fullsim.coverage",true)'
#      - name: postprocess
#        run: root -b -q macro/ci/postprocess_coverage.C'("out/fullsim.coverage.root")'
#      - name: artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: fullsim-coverage-plots
#          path: |
#            out/fullsim.coverage.images
