name: ci

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:

  build:
    runs-on: [ ubuntu-latest ]
    container:
      image: cjdilks/largex-eic:dev
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: config
        run: |
          source env.sh
          echo "MSTWPDF_HOME=${MSTWPDF_HOME}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MSTWPDF_HOME}" >> $GITHUB_ENV
          more $GITHUB_ENV
      - name: compile
        run: make

  test-coverage:
    needs: [ build ]
    runs-on: [ ubuntu-latest ]
    container:
      image: cjdilks/largex-eic:dev
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: config
        run: |
          source env.sh
          echo "MSTWPDF_HOME=${MSTWPDF_HOME}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MSTWPDF_HOME}" >> $GITHUB_ENV
          more $GITHUB_ENV
      - name: compile
        run: make
      - name: analysis
        run: root -b -q macro/ci/analysis_xqbins.C
      - name: postprocess
        run: root -b -q macro/ci/postprocess_xqbins_draw.C
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-plots
          path: |
            out/coverage.images

  test-y-minima:
    needs: [ build ]
    runs-on: [ ubuntu-latest ]
    container:
      image: cjdilks/largex-eic:dev
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: config
        run: |
          source env.sh
          echo "MSTWPDF_HOME=${MSTWPDF_HOME}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MSTWPDF_HOME}" >> $GITHUB_ENV
          more $GITHUB_ENV
      - name: compile
        run: make
      - name: analysis
        run: root -b -q macro/ci/analysis_yRatio.C
      - name: postprocess
        run: root -b -q macro/ci/postprocess_yRatio.C
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: y-minima-ratio-plots
          path: |
            out/yRatio.images/yRatio*.png
