name: ci

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:

  build:
    runs-on: [ ubuntu-latest ]
    container:
      image: cjdilks/largex-eic:dev
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: config
        run: |
          source env.sh
          echo "MSTWPDF_HOME=${MSTWPDF_HOME}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MSTWPDF_HOME}" >> $GITHUB_ENV
          more $GITHUB_ENV
      - name: compile
        run: make

  fastsim-coverage:
    needs: [ build ]
    runs-on: [ ubuntu-latest ]
    container:
      image: cjdilks/largex-eic:dev
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: config
        run: |
          source env.sh
          echo "MSTWPDF_HOME=${MSTWPDF_HOME}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MSTWPDF_HOME}" >> $GITHUB_ENV
          more $GITHUB_ENV
      - name: compile
        run: make
      - name: analysis
        run: root -b -q macro/ci/analysis_xqbins.C
      - name: postprocess
        run: root -b -q macro/ci/postprocess_xqbins_draw.C
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fastsim-coverage-plots
          path: |
            out/coverage.images

  fastsim-y-minima:
    needs: [ build ]
    runs-on: [ ubuntu-latest ]
    container:
      image: cjdilks/largex-eic:dev
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: config
        run: |
          source env.sh
          echo "MSTWPDF_HOME=${MSTWPDF_HOME}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MSTWPDF_HOME}" >> $GITHUB_ENV
          more $GITHUB_ENV
      - name: compile
        run: make
      - name: analysis
        run: root -b -q macro/ci/analysis_yRatio.C
      - name: postprocess
        run: root -b -q macro/ci/postprocess_yRatio.C
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fastsim-y-minima-ratio-plots
          path: |
            out/yRatio.images/yRatio*.png

  fastsim-resolutions:
    needs: [ build ]
    runs-on: [ ubuntu-latest ]
    container:
      image: cjdilks/largex-eic:dev
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: config
        run: |
          source env.sh
          echo "MSTWPDF_HOME=${MSTWPDF_HOME}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MSTWPDF_HOME}" >> $GITHUB_ENV
          more $GITHUB_ENV
      - name: compile
        run: make
      - name: analysis
        run: root -b -q macro/ci/analysis_resolution.C
      - name: postprocess
        run: root -b -q macro/ci/postprocess_resolution.C
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fastsim-resolution-plots
          path: |
            out/resolution.images/*.pdf

  fullsim-coverage:
    needs: [ build ]
    runs-on: [ ubuntu-latest ]
    container:
      image: cjdilks/largex-eic:dev
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: config
        run: |
          source env.sh
          echo "MSTWPDF_HOME=${MSTWPDF_HOME}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MSTWPDF_HOME}" >> $GITHUB_ENV
          more $GITHUB_ENV
      - name: compile
        run: make
      - name: analysis
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        run: root -b -q macro/ci/analysis_dd4hep.C
      - name: postprocess
        run: root -b -q macro/ci/postprocess_dd4hep_draw.C
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fullsim-coverage-plots
          path: |
            out/fullsim.coverage.images
