name: ci

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:

# build test
  build:
    runs-on: [ ubuntu-latest ]
    container:
      image: cjdilks/largex-eic:dev
      options: --user root
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: config
        run: |
          source env.sh
          echo "MSTWPDF_HOME=${MSTWPDF_HOME}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MSTWPDF_HOME}" >> $GITHUB_ENV
      - name: compile
        run: make
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            LargexDict_rdict.pcm
            libLargex.so
            mstwpdf/*.o
            mstwpdf/*.so
            src/LargexDict.cxx

# run benchmark macros matrix for fast and full simulation
# - all files in matrix are w.r.t. path macro/ci/
  benchmarks:
    needs: [ build ]
    runs-on: [ ubuntu-latest ]
    container:
      image: cjdilks/largex-eic:dev
      options: --user root
    strategy:
      matrix:
        name: [ coverage, y-minima, resolutions ]
        mode: [ fastsim, fullsim ]
        include:
          - name: fastsim
            config: files.config
          - name: fullsim
            config: s3files.config
          - name: coverage
            amacro: analysis_coverage.C
            pmacro: postprocess_coverage.C
          - name: y-minima
            amacro: analysis_yRatio.C
            pmacro: postprocess_yRatio.C
          - name: resolutions
            amacro: analysis_resolution.C
            pmacro: postprocess_resolution.C
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: config
        run: |
          source env.sh
          echo "MSTWPDF_HOME=${MSTWPDF_HOME}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${MSTWPDF_HOME}" >> $GITHUB_ENV
      - name: get-artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
      - name: analysis
        env:
          S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
          S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
        run: root -b -q macro/ci/${{ matrix.amacro }}'("macro/ci/${{ matrix.config }}",5,41,25,"${{ matrix.name }}.${{ matrix.mode }}")'
      - name: postprocess
        run: root -b -q macro/ci/${{ matrix.pmacro }}'("out/${{ matrix.name }}.${{ matrix.mode }}.root")'
      - name: artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}-${{ matrix.mode }}-plots
          path: out/${{ matrix.name }}.${{ matrix.mode }}.images

# collect artifacts into one directory
  collect:
    if: ${{ always() }}
    needs: [ benchmarks ]
    runs-on: [ ubuntu-latest ]
    steps:
      - name: download
        uses: actions/download-artifact@v2
        with:
          path: results
      - name: cull
        run: rm -rv results/build-artifacts
      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: _FULL_RESULTS
          path: results
